<?php
$WCONFIG_lateTime="09:35:00";//迟到时间
$WCONFIG["client_version"]='1.0.0.8';//客户端版本
$WCONFIG["updater_version"]='1.0.0.8';//更新器版本
$WCONFIG["request_time"]=30000;//客户端请求间隔（毫秒）
$WCONFIG["late"]=strtotime(date($WCONFIG_lateTime));
//每天特定时间请求地址
$WCONFIG["tasklist"]=array(
array(APP_URL."tpl/notice/msgbox.html#?c=webservice&a=loginJump&type=msg&act=todayWork&userAccount={@userAccount}&userPwd={@userPwd}","10:30:00"),
array(APP_URL."tpl/notice/msgbox.html#?c=webservice&a=loginJump&type=msg&act=delayWork&userAccount={@userAccount}&userPwd={@userPwd}","14:00:00"),
array(APP_URL."tpl/notice/msgbox.html#?c=webservice&a=loginJump&type=msg&act=unSubmitWork&userAccount={@userAccount}&userPwd={@userPwd}","17:30:00")
);
//更新的文件地址列表
$WCONFIG["updatelist"]=array(
array(APP_URL."download/update/NiePMS.exe"),
array(APP_URL."download/update/setting.exe"),
array(APP_URL."download/update/NIECORE.dll"),
array(APP_URL."download/update/NIEmessage.exe")
);
?>